version: "3.8"  # Рекомендуется указывать версию конфигурации

services:
  db:
    image: postgres:15
    container_name: dental-store-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./DB:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network

#  dental-store:
#    build: .
#    container_name: dental-store-app
#    restart: unless-stopped
#    command: sh -c "python dentalstore/manage.py migrate && python dentalstore/manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/app
#    environment:
#      DEBUG: '0'
#      DATABASE_NAME: ${DB_NAME}
#      DATABASE_USER: ${DB_USER}
#      DATABASE_PASSWORD: ${DB_PASSWORD}
#      DATABASE_HOST: ${DB_HOST}
#      DATABASE_PORT: ${DB_PORT}
#    expose:
#      - "8000"
#    depends_on:
#      - db
#    networks:
#      - app-network
#
#  caddy:
#    image: caddy:latest
#    container_name: caddy
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - caddy_data:/data
#      - caddy_config:/config
#      - ./Caddyfile:/etc/caddy/Caddyfile
#    depends_on:
#      - dental-store
#    networks:
#      - app-network
#
#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer
#    restart: always
#    ports:
#      - "9000:9000"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  caddy_data:
#  caddy_config:
#  portainer_data: